version: '3.4'
services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=roger
      - RABBITMQ_DEFAULT_PASS=rabbit
  consumer:
    build: './consumer-net/'
    restart: always
    ports:
      - "8010:80"
    depends_on:
      - rabbit
  producer:
    build: './producer-net'
    restart: always
    ports:
      - "8020:8080"
    depends_on:
      - rabbit